// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodePduBackendModels(in *jlexer.Lexer, out *SNssai) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sst":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sst = int(in.Int())
			}
		case "sd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sd = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodePduBackendModels(out *jwriter.Writer, in SNssai) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sst\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Sst))
	}
	{
		const prefix string = ",\"sd\":"
		out.RawString(prefix)
		out.String(string(in.Sd))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SNssai) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodePduBackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SNssai) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodePduBackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SNssai) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodePduBackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SNssai) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodePduBackendModels(l, v)
}
func easyjsonD2b7633eDecodePduBackendModels1(in *jlexer.Lexer, out *HeartbeatMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodePduBackendModels1(out *jwriter.Writer, in HeartbeatMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HeartbeatMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodePduBackendModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HeartbeatMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodePduBackendModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HeartbeatMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodePduBackendModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HeartbeatMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodePduBackendModels1(l, v)
}
func easyjsonD2b7633eDecodePduBackendModels2(in *jlexer.Lexer, out *CreateSessionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "smContextRef":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SmContextRef = string(in.String())
			}
		case "supi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Supi = string(in.String())
			}
		case "pduSessionId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PduSessionId = int(in.Int())
			}
		case "handledBy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HandledBy = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodePduBackendModels2(out *jwriter.Writer, in CreateSessionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"smContextRef\":"
		out.RawString(prefix[1:])
		out.String(string(in.SmContextRef))
	}
	{
		const prefix string = ",\"supi\":"
		out.RawString(prefix)
		out.String(string(in.Supi))
	}
	{
		const prefix string = ",\"pduSessionId\":"
		out.RawString(prefix)
		out.Int(int(in.PduSessionId))
	}
	{
		const prefix string = ",\"handledBy\":"
		out.RawString(prefix)
		out.String(string(in.HandledBy))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSessionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodePduBackendModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSessionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodePduBackendModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSessionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodePduBackendModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSessionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodePduBackendModels2(l, v)
}
func easyjsonD2b7633eDecodePduBackendModels3(in *jlexer.Lexer, out *CreateSessionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "supi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Supi = string(in.String())
			}
		case "gpsi":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Gpsi = string(in.String())
			}
		case "pduSessionId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PduSessionId = int(in.Int())
			}
		case "dnn":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dnn = string(in.String())
			}
		case "sNssai":
			if in.IsNull() {
				in.Skip()
				out.SNssai = nil
			} else {
				if out.SNssai == nil {
					out.SNssai = new(SNssai)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.SNssai).UnmarshalEasyJSON(in)
				}
			}
		case "servingNfId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServingNfId = string(in.String())
			}
		case "anType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AnType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodePduBackendModels3(out *jwriter.Writer, in CreateSessionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"supi\":"
		out.RawString(prefix[1:])
		out.String(string(in.Supi))
	}
	{
		const prefix string = ",\"gpsi\":"
		out.RawString(prefix)
		out.String(string(in.Gpsi))
	}
	{
		const prefix string = ",\"pduSessionId\":"
		out.RawString(prefix)
		out.Int(int(in.PduSessionId))
	}
	{
		const prefix string = ",\"dnn\":"
		out.RawString(prefix)
		out.String(string(in.Dnn))
	}
	{
		const prefix string = ",\"sNssai\":"
		out.RawString(prefix)
		if in.SNssai == nil {
			out.RawString("null")
		} else {
			(*in.SNssai).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"servingNfId\":"
		out.RawString(prefix)
		out.String(string(in.ServingNfId))
	}
	{
		const prefix string = ",\"anType\":"
		out.RawString(prefix)
		out.String(string(in.AnType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSessionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodePduBackendModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSessionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodePduBackendModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSessionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodePduBackendModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSessionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodePduBackendModels3(l, v)
}
